import { Router, type IRouter } from "express";
import healthRouter from "./health";
import projectsRouter from "./projects";
import dashboardRouter from "./dashboard";
import booksRouter from "./books";
import chaptersRouter from "./chapters";
import scenesRouter from "./scenes";
import charactersRouter from "./characters";
import locationsRouter from "./locations";
import worldRulesRouter from "./worldRules";
import memoryRouter from "./memory";
import timelineRouter from "./timeline";
import styleGuideRouter from "./styleGuide";
import profileRouter from "./profile";
import sceneVersionsRouter from "./sceneVersions";
import aiRouter from "./ai";
import aiCredentialsRouter from "./aiCredentials";
import continuityAlertsRouter from "./continuityAlerts";

const router: IRouter = Router();

router.use(healthRouter);
router.use(profileRouter);
router.use(projectsRouter);
router.use(dashboardRouter);
router.use(booksRouter);
router.use(chaptersRouter);
router.use(scenesRouter);
router.use(charactersRouter);
router.use(locationsRouter);
router.use(worldRulesRouter);
router.use(memoryRouter);
router.use(timelineRouter);
router.use(styleGuideRouter);
router.use(sceneVersionsRouter);
router.use(aiRouter);
router.use(aiCredentialsRouter);
router.use(continuityAlertsRouter);

export default router;
